### ISSUE TITLE
Client certificate request causes crash

### ISSUE THREAD

**Issue by LowLevelJet** [tobykurien/WebApps#61]
I would have put this in the other issue had I known, but for sites that use TLS certificate login, WebApps crashes. Maybe you could implement the callbacks for this too? Or at least prevent the crash...

I know the stock browser (Android 4.2) works fine, and the cert for the site in question is loaded on my device.

Sorry for the spam!

**Comment by tobykurien** [comment]
Not spam, these are actually 2 separate issues. I'll need to find a site with client cert auth to test on. I would like WebApps to support this authentication method.

**Comment by tobykurien** [comment]
@LowLevelJet if possible, could you please provide me with an example website where this crash happens?

**Comment by LowLevelJet** [comment]
I can't as it's a private server. I can try to get a stack trace out of WebApps. Are you saying you believe that client cert authentication should work? I am using Android 4.2.2 so maybe it would help you to be able to reproduce the issue by using the Android Emulator with that version of Android.

**Comment by LowLevelJet** [comment]
Okay so looking into this I believe it might be a duplicate of #62. I don't understand why that issue didn't crop up when I visited another path on the same server that was SSL-secured but not client cert-enabled. The certificate should be trusted, it's not self-signed as such but it's issued by 'personal' CA that has been installed into the Android keychain. Nonetheless, I will test v2.9 when it hits F-Droid and let you know.

Here is the stack trace:

02-01 16:51:59.466 13631 13631 D AndroidRuntime: Shutting down VM
02-01 16:51:59.466 13631 13631 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41db3930)
02-01 16:51:59.486 13631 13631 E AndroidRuntime: FATAL EXCEPTION: main
02-01 16:51:59.486 13631 13631 E AndroidRuntime: java.lang.NullPointerException
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at com.tobykurien.webapps.utils.CertificateUtils.updateCertificate(CertificateUtils.xtend:42)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at com.tobykurien.webapps.activity.WebAppActivity.onPageLoadDone(WebAppActivity.xtend:266)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at com.tobykurien.webapps.webviewclient.WebClient.onPageFinished(WebClient.xtend:70)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:323)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:137)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5227)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at java.lang.reflect.Method.invokeNative(Native Method)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:511)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at dalvik.system.NativeStart.main(Native Method)
02-01 16:51:59.486  1108  1989 W ActivityManager:   Force finishing activity com.tobykurien.webapps/.activity.WebAppActivity

**Comment by tobykurien** [comment]
Yup this should be fixed with v2.9. Thanks for the stack trace.

On 2 February 2017 00:02:59 GMT+02:00, LowLevelJet <notifications@github.com> wrote:
>Okay so looking into this I believe it might be a duplicate of #62. I
>don't understand why that issue didn't crop up when I visited another
>path on the same server that was SSL-secured but not client
>cert-enabled. The certificate should be trusted, it's not self-signed
>as such but it's issued by 'personal' CA that has been installed into
>the Android keychain. Nonetheless, I will test v2.9 when it hits
>F-Droid and let you know.
>
>Here is the stack trace:
>
>02-01 16:51:59.466 13631 13631 D AndroidRuntime: Shutting down VM
>02-01 16:51:59.466 13631 13631 W dalvikvm: threadid=1: thread exiting
>with uncaught exception (group=0x41db3930)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime: FATAL EXCEPTION: main
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:
>java.lang.NullPointerException
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>com.tobykurien.webapps.utils.CertificateUtils.updateCertificate(CertificateUtils.xtend:42)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>com.tobykurien.webapps.activity.WebAppActivity.onPageLoadDone(WebAppActivity.xtend:266)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>com.tobykurien.webapps.webviewclient.WebClient.onPageFinished(WebClient.xtend:70)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:323)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>android.os.Handler.dispatchMessage(Handler.java:99)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>android.os.Looper.loop(Looper.java:137)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>android.app.ActivityThread.main(ActivityThread.java:5227)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>java.lang.reflect.Method.invokeNative(Native Method)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>java.lang.reflect.Method.invoke(Method.java:511)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>com.android.internal.os.ZygoteInit.main(ZygoteInit.java:562)
>02-01 16:51:59.486 13631 13631 E AndroidRuntime:        at
>dalvik.system.NativeStart.main(Native Method)
>02-01 16:51:59.486  1108  1989 W ActivityManager:   Force finishing
>activity com.tobykurien.webapps/.activity.WebAppActivity
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tobykurien/WebApps/issues/61#issuecomment-276797399

-- 
tobykurien.com | @tobykurien

**Comment by LowLevelJet** [comment]
It doesn't crash, but it still doesn't work. And it looks like implementing it is a landmine of hidden APIs, introduced WebView bugs, and issue reports ignored by Google: http://stackoverflow.com/questions/15588851/android-webview-with-client-certificate/15590041

You can support it on 5+ only, or use reflection to get at the hidden API for 4.x. I'd certainly prefer the latter but understand if you are unwilling to do that. There's also apparently a bug in Android 4.4 WebView that precludes it from working at all.
